-- MySQL Script generated by MySQL Workbench
-- Thu 09 Jun 2022 11:01:57 PM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wish` ;
USE `wish` ;

-- -----------------------------------------------------
-- Table `wish`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish`.`user` (
  `uid` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  `is_active` TINYINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wish`.`space`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish`.`space` (
  `uid` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  `is_active` TINYINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_wishspace_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_wishspace_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `wish`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wish`.`wish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish`.`wish` (
  `uid` VARCHAR(45) NOT NULL,
  `space_id` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `is_active` VARCHAR(45) NOT NULL,
  `price` FLOAT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `user_responsible_id` VARCHAR(45) NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_wish_space_idx` (`space_id` ASC) VISIBLE,
  INDEX `fk_wish_user_idx` (`user_responsible_id` ASC) VISIBLE,
  CONSTRAINT `fk_wish_space`
    FOREIGN KEY (`space_id`)
    REFERENCES `wish`.`space` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wish_user`
    FOREIGN KEY (`user_responsible_id`)
    REFERENCES `wish`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wish`.`applicant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish`.`applicant` (
  `uid` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `wish_id` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_applicant_wish_idx` (`wish_id` ASC) VISIBLE,
  INDEX `fk_applicant_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_applicant_wish`
    FOREIGN KEY (`wish_id`)
    REFERENCES `wish`.`wish` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicant_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `wish`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
